

spring.cloud:
    azure:
      active-directory:
        enabled: true
        profile:
          tenant-id: 53695c6a-e1de-42b9-be99-97f60ccfd8b0
        credential:
          client-id: 1b5a6020-ccdf-4ef2-9331-11c730deb5ff
        app-id-uri: "api://1b5a6020-ccdf-4ef2-9331-11c730deb5ff"



