name: Build and push Docker image

on:
  push:
    branches: [ main, master, 'releases/**' ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      VERSION: v1.0.0

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - name: Set up JDK 21 and cache Maven
      #   uses: actions/setup-java@v4
      #   with:
      #     distribution: temurin
      #     java-version: '21'
      #     cache: 'maven'

      # - name: Cache Maven repository
      #   uses: actions/cache@v4
      #   with:
      #     path: ~/.m2/repository
      #     key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
      #     restore-keys: |
      #       ${{ runner.os }}-m2-

      # - name: Build with Maven
      #   run: mvn -B package -DskipTests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: ./lab-oauth2-spa
          file: ./lab-oauth2-spa/Dockerfile
          push: true
          tags: |
            ghcr.io/labs/lab-oauth2/${{ github.repository }}:${{ env.VERSION }}
            ghcr.io/labs/lab-oauth2/${{ github.repository }}:${{ github.sha }}
          # optionally enable build cache
          cache-from: type=gha
          cache-to: type=gha,mode=max